com.is1.proyecto.models.Persona:default
com.is1.proyecto.models.Carrera:default
com.is1.proyecto.models.Estudiante:default
com.is1.proyecto.models.PlanDeEstudios:default
com.is1.proyecto.models.PeriodoAcademico:default
com.is1.proyecto.models.ExamenFinal:default
com.is1.proyecto.models.User:default
com.is1.proyecto.models.Admin:default
com.is1.proyecto.models.Docente:default
com.is1.proyecto.models.Materia:default
